name: build&release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parch build Action
        uses: parchlinux/build-action@0.1.0
